### ISSUE TITLE
Migrate to geocities

### ISSUE THREAD

**Issue by tishkhan** [moritonal/a-twitch-wedding#1]
1. Blink tags
2. Marquee Tags
3. Page view counter
4. Weather widget
5. Guest book
6. bitcoin donation link

**Comment by moritonal** [comment]
Great points, will look into.

**Comment by moritonal** [comment]
Can't fix, Geocities has been closed down! https://www.cnet.com/news/geocities-dies-in-march-2019-and-with-it-a-piece-of-internet-history/
